// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders:         number;
  paidOrder:              number;
  notPaidOrders:          number;
  numberOfClients:        number;
  numberOfProducts:       number;
  productWithNoInventory: number;
  lowInventory:           number;
}
